package centaur.db;
// Generated Feb 23, 2016 9:47:25 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Candidate generated by hbm2java
 */
public class Candidate implements java.io.Serializable {

	private int idNode;
	private Node node;
	private BigDecimal ouflowElevation;
	private Set floodeds = new HashSet(0);

	public Candidate() {
	}

	public Candidate(Node node, BigDecimal ouflowElevation) {
		this.node = node;
		this.ouflowElevation = ouflowElevation;
	}

	public Candidate(Node node, BigDecimal ouflowElevation, Set floodeds) {
		this.node = node;
		this.ouflowElevation = ouflowElevation;
		this.floodeds = floodeds;
	}

	public int getIdNode() {
		return this.idNode;
	}

	public void setIdNode(int idNode) {
		this.idNode = idNode;
	}

	public Node getNode() {
		return this.node;
	}

	public void setNode(Node node) {
		this.node = node;
	}

	public BigDecimal getOuflowElevation() {
		return this.ouflowElevation;
	}

	public void setOuflowElevation(BigDecimal ouflowElevation) {
		this.ouflowElevation = ouflowElevation;
	}

	public Set getFloodeds() {
		return this.floodeds;
	}

	public void setFloodeds(Set floodeds) {
		this.floodeds = floodeds;
	}

}
