package centaur.db;
// Generated Mar 16, 2016 11:11:21 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Candidate generated by hbm2java
 */
public class Candidate implements java.io.Serializable {

	private int idNode;
	private Node node;
	private BigDecimal outflowElevation;
	private BigDecimal servedArea;
	private Set floodeds = new HashSet(0);

	public Candidate() {
	}

	public Candidate(Node node, BigDecimal outflowElevation) {
		this.node = node;
		this.outflowElevation = outflowElevation;
	}

	public Candidate(Node node, BigDecimal outflowElevation, BigDecimal servedArea, Set floodeds) {
		this.node = node;
		this.outflowElevation = outflowElevation;
		this.servedArea = servedArea;
		this.floodeds = floodeds;
	}

	public int getIdNode() {
		return this.idNode;
	}

	public void setIdNode(int idNode) {
		this.idNode = idNode;
	}

	public Node getNode() {
		return this.node;
	}

	public void setNode(Node node) {
		this.node = node;
	}

	public BigDecimal getOutflowElevation() {
		return this.outflowElevation;
	}

	public void setOutflowElevation(BigDecimal outflowElevation) {
		this.outflowElevation = outflowElevation;
	}

	public BigDecimal getServedArea() {
		return this.servedArea;
	}

	public void setServedArea(BigDecimal servedArea) {
		this.servedArea = servedArea;
	}

	public Set getFloodeds() {
		return this.floodeds;
	}

	public void setFloodeds(Set floodeds) {
		this.floodeds = floodeds;
	}

}
