package centaur.db;
// Generated Feb 3, 2016 11:43:24 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Conduit generated by hbm2java
 */
public class Conduit implements java.io.Serializable {

	private int idLink;
	private Link link;
	private String name;
	private BigDecimal length;
	private BigDecimal roughness;
	private BigDecimal inOffset;
	private BigDecimal outOffset;
	private BigDecimal initFlow;
	private BigDecimal maxFlow;
	private Xsection xsection;

	public Conduit() {
	}

	public Conduit(Link link) {
		this.link = link;
	}

	public Conduit(Link link, String name, BigDecimal length, BigDecimal roughness, BigDecimal inOffset,
			BigDecimal outOffset, BigDecimal initFlow, BigDecimal maxFlow, Xsection xsection) {
		this.link = link;
		this.name = name;
		this.length = length;
		this.roughness = roughness;
		this.inOffset = inOffset;
		this.outOffset = outOffset;
		this.initFlow = initFlow;
		this.maxFlow = maxFlow;
		this.xsection = xsection;
	}

	public int getIdLink() {
		return this.idLink;
	}

	public void setIdLink(int idLink) {
		this.idLink = idLink;
	}

	public Link getLink() {
		return this.link;
	}

	public void setLink(Link link) {
		this.link = link;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getLength() {
		return this.length;
	}

	public void setLength(BigDecimal length) {
		this.length = length;
	}

	public BigDecimal getRoughness() {
		return this.roughness;
	}

	public void setRoughness(BigDecimal roughness) {
		this.roughness = roughness;
	}

	public BigDecimal getInOffset() {
		return this.inOffset;
	}

	public void setInOffset(BigDecimal inOffset) {
		this.inOffset = inOffset;
	}

	public BigDecimal getOutOffset() {
		return this.outOffset;
	}

	public void setOutOffset(BigDecimal outOffset) {
		this.outOffset = outOffset;
	}

	public BigDecimal getInitFlow() {
		return this.initFlow;
	}

	public void setInitFlow(BigDecimal initFlow) {
		this.initFlow = initFlow;
	}

	public BigDecimal getMaxFlow() {
		return this.maxFlow;
	}

	public void setMaxFlow(BigDecimal maxFlow) {
		this.maxFlow = maxFlow;
	}

	public Xsection getXsection() {
		return this.xsection;
	}

	public void setXsection(Xsection xsection) {
		this.xsection = xsection;
	}

}
