package centaur.db;
// Generated Jun 17, 2016 8:52:13 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Contribution generated by hbm2java
 */
public class Contribution implements java.io.Serializable {

	private Integer id;
	private Candidate candidate;
	private Subcatchment subcatchment;
	private BigDecimal value;

	public Contribution() {
	}

	public Contribution(Candidate candidate, Subcatchment subcatchment, BigDecimal value) {
		this.candidate = candidate;
		this.subcatchment = subcatchment;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	public Subcatchment getSubcatchment() {
		return this.subcatchment;
	}

	public void setSubcatchment(Subcatchment subcatchment) {
		this.subcatchment = subcatchment;
	}

	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

}
