package centaur.db;
// Generated Apr 13, 2016 5:05:48 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Contribution generated by hbm2java
 */
public class Contribution implements java.io.Serializable {

	private Integer id;
	private Candidate candidate;
	private Subcatchment subcatchment;
	//private int idSubcatchment;
	private BigDecimal value;

	public Contribution() {
	}

	public Contribution(Candidate candidate, Subcatchment subcatchment, /*int idSubcatchment,*/ BigDecimal value) {
		this.candidate = candidate;
		this.subcatchment = subcatchment;
		//this.idSubcatchment = idSubcatchment;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	public Subcatchment getSubcatchment() {
		return this.subcatchment;
	}

	public void setSubcatchment(Subcatchment subcatchment) {
		this.subcatchment = subcatchment;
	}

	/*public int getIdSubcatchment() {
		return this.idSubcatchment;
	}

	public void setIdSubcatchment(int idSubcatchment) {
		this.idSubcatchment = idSubcatchment;
	}*/

	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

}
