package centaur.db;
// Generated 24-Jan-2017 16:06:00 by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;

/**
 * ContributionTemp generated by hbm2java
 */
public class ContributionTemp implements java.io.Serializable {

	private int id;
	private Candidate candidate;
	private Subcatchment subcatchment;
	private BigDecimal value;

	public ContributionTemp() {
	}

	public ContributionTemp(int id, Candidate candidate, Subcatchment subcatchment, BigDecimal value) {
		this.id = id;
		this.candidate = candidate;
		this.subcatchment = subcatchment;
		this.value = value;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	public Subcatchment getSubcatchment() {
		return this.subcatchment;
	}

	public void setSubcatchment(Subcatchment subcatchment) {
		this.subcatchment = subcatchment;
	}

	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

}
