package centaur.db;
// Generated Feb 15, 2016 9:54:40 AM by Hibernate Tools 4.3.1.Final

/**
 * Coordinates generated by hbm2java
 */
public class Coordinates implements java.io.Serializable {

	private CoordinatesId id;
	private Node node;

	public Coordinates() {
	}

	public Coordinates(CoordinatesId id) {
		this.id = id;
	}

	public Coordinates(CoordinatesId id, Node node) {
		this.id = id;
		this.node = node;
	}

	public CoordinatesId getId() {
		return this.id;
	}

	public void setId(CoordinatesId id) {
		this.id = id;
	}

	public Node getNode() {
		return this.node;
	}

	public void setNode(Node node) {
		this.node = node;
	}

}
