package centaur.db;
// Generated Feb 2, 2016 9:45:06 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Curve generated by hbm2java
 */
public class Curve implements java.io.Serializable {

	private int id;
	private String name;
	private String type;
	private CurveParameter curveParameter;
	private Set storages = new HashSet(0);

	public Curve() {
	}

	public Curve(int id) {
		this.id = id;
	}

	public Curve(int id, String name, String type, CurveParameter curveParameter, Set storages) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.curveParameter = curveParameter;
		this.storages = storages;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public CurveParameter getCurveParameter() {
		return this.curveParameter;
	}

	public void setCurveParameter(CurveParameter curveParameter) {
		this.curveParameter = curveParameter;
	}

	public Set getStorages() {
		return this.storages;
	}

	public void setStorages(Set storages) {
		this.storages = storages;
	}

}
