package centaur.db;
// Generated Feb 2, 2016 9:45:06 AM by Hibernate Tools 4.3.1.Final

/**
 * LinkCoordinates generated by hbm2java
 */
public class LinkCoordinates implements java.io.Serializable {

	private LinkCoordinatesId id;

	public LinkCoordinates() {
	}

	public LinkCoordinates(LinkCoordinatesId id) {
		this.id = id;
	}

	public LinkCoordinatesId getId() {
		return this.id;
	}

	public void setId(LinkCoordinatesId id) {
		this.id = id;
	}

}
