package centaur.db;
// Generated Feb 2, 2016 9:45:06 AM by Hibernate Tools 4.3.1.Final

/**
 * Link generated by hbm2java
 */
public class Link implements java.io.Serializable {

	private int id;
	private Node nodeByIdNodeTo;
	private Node nodeByIdNodeFrom;
	private Weir weir;
	private Conduit conduit;
	private Pump pump;

	public Link() {
	}

	public Link(int id) {
		this.id = id;
	}

	public Link(int id, Node nodeByIdNodeTo, Node nodeByIdNodeFrom, Weir weir, Conduit conduit, Pump pump) {
		this.id = id;
		this.nodeByIdNodeTo = nodeByIdNodeTo;
		this.nodeByIdNodeFrom = nodeByIdNodeFrom;
		this.weir = weir;
		this.conduit = conduit;
		this.pump = pump;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Node getNodeByIdNodeTo() {
		return this.nodeByIdNodeTo;
	}

	public void setNodeByIdNodeTo(Node nodeByIdNodeTo) {
		this.nodeByIdNodeTo = nodeByIdNodeTo;
	}

	public Node getNodeByIdNodeFrom() {
		return this.nodeByIdNodeFrom;
	}

	public void setNodeByIdNodeFrom(Node nodeByIdNodeFrom) {
		this.nodeByIdNodeFrom = nodeByIdNodeFrom;
	}

	public Weir getWeir() {
		return this.weir;
	}

	public void setWeir(Weir weir) {
		this.weir = weir;
	}

	public Conduit getConduit() {
		return this.conduit;
	}

	public void setConduit(Conduit conduit) {
		this.conduit = conduit;
	}

	public Pump getPump() {
		return this.pump;
	}

	public void setPump(Pump pump) {
		this.pump = pump;
	}

}
