package centaur.db;
// Generated Feb 3, 2016 11:43:24 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * NodeCoordinatesId generated by hbm2java
 */
public class NodeCoordinatesId implements java.io.Serializable {

	private Integer idNode;
	private BigDecimal x;
	private BigDecimal y;

	public NodeCoordinatesId() {
	}

	public NodeCoordinatesId(Integer idNode, BigDecimal x, BigDecimal y) {
		this.idNode = idNode;
		this.x = x;
		this.y = y;
	}

	public Integer getIdNode() {
		return this.idNode;
	}

	public void setIdNode(Integer idNode) {
		this.idNode = idNode;
	}

	public BigDecimal getX() {
		return this.x;
	}

	public void setX(BigDecimal x) {
		this.x = x;
	}

	public BigDecimal getY() {
		return this.y;
	}

	public void setY(BigDecimal y) {
		this.y = y;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NodeCoordinatesId))
			return false;
		NodeCoordinatesId castOther = (NodeCoordinatesId) other;

		return ((this.getIdNode() == castOther.getIdNode()) || (this.getIdNode() != null
				&& castOther.getIdNode() != null && this.getIdNode().equals(castOther.getIdNode())))
				&& ((this.getX() == castOther.getX())
						|| (this.getX() != null && castOther.getX() != null && this.getX().equals(castOther.getX())))
				&& ((this.getY() == castOther.getY())
						|| (this.getY() != null && castOther.getY() != null && this.getY().equals(castOther.getY())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdNode() == null ? 0 : this.getIdNode().hashCode());
		result = 37 * result + (getX() == null ? 0 : this.getX().hashCode());
		result = 37 * result + (getY() == null ? 0 : this.getY().hashCode());
		return result;
	}

}
