package centaur.db;
// Generated Feb 2, 2016 9:45:06 AM by Hibernate Tools 4.3.1.Final

/**
 * NodeCoordinates generated by hbm2java
 */
public class NodeCoordinates implements java.io.Serializable {

	private NodeCoordinatesId id;

	public NodeCoordinates() {
	}

	public NodeCoordinates(NodeCoordinatesId id) {
		this.id = id;
	}

	public NodeCoordinatesId getId() {
		return this.id;
	}

	public void setId(NodeCoordinatesId id) {
		this.id = id;
	}

}
