package centaur.db;
// Generated Feb 2, 2016 9:45:06 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Node generated by hbm2java
 */
public class Node implements java.io.Serializable {

	private int id;
	private BigDecimal elevation;
	private Junction junction;
	private Outfall outfall;
	private Set linksForIdNodeTo = new HashSet(0);
	private Set linksForIdNodeFrom = new HashSet(0);
	private Storage storage;
	private Set subcatchments = new HashSet(0);

	public Node() {
	}

	public Node(int id) {
		this.id = id;
	}

	public Node(int id, BigDecimal elevation, Junction junction, Outfall outfall, Set linksForIdNodeTo,
			Set linksForIdNodeFrom, Storage storage, Set subcatchments) {
		this.id = id;
		this.elevation = elevation;
		this.junction = junction;
		this.outfall = outfall;
		this.linksForIdNodeTo = linksForIdNodeTo;
		this.linksForIdNodeFrom = linksForIdNodeFrom;
		this.storage = storage;
		this.subcatchments = subcatchments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public BigDecimal getElevation() {
		return this.elevation;
	}

	public void setElevation(BigDecimal elevation) {
		this.elevation = elevation;
	}

	public Junction getJunction() {
		return this.junction;
	}

	public void setJunction(Junction junction) {
		this.junction = junction;
	}

	public Outfall getOutfall() {
		return this.outfall;
	}

	public void setOutfall(Outfall outfall) {
		this.outfall = outfall;
	}

	public Set getLinksForIdNodeTo() {
		return this.linksForIdNodeTo;
	}

	public void setLinksForIdNodeTo(Set linksForIdNodeTo) {
		this.linksForIdNodeTo = linksForIdNodeTo;
	}

	public Set getLinksForIdNodeFrom() {
		return this.linksForIdNodeFrom;
	}

	public void setLinksForIdNodeFrom(Set linksForIdNodeFrom) {
		this.linksForIdNodeFrom = linksForIdNodeFrom;
	}

	public Storage getStorage() {
		return this.storage;
	}

	public void setStorage(Storage storage) {
		this.storage = storage;
	}

	public Set getSubcatchments() {
		return this.subcatchments;
	}

	public void setSubcatchments(Set subcatchments) {
		this.subcatchments = subcatchments;
	}

}
