package centaur.db;
// Generated Feb 8, 2016 9:29:23 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Pump generated by hbm2java
 */
public class Pump implements java.io.Serializable {

	private int idLink;
	private Link link;
	private String name;
	private String pumpCurve;
	private String status;
	private BigDecimal startup;
	private BigDecimal shutoff;

	public Pump() {
	}

	public Pump(Link link) {
		this.link = link;
	}

	public Pump(Link link, String name, String pumpCurve, String status, BigDecimal startup, BigDecimal shutoff) {
		this.link = link;
		this.name = name;
		this.pumpCurve = pumpCurve;
		this.status = status;
		this.startup = startup;
		this.shutoff = shutoff;
	}

	public int getIdLink() {
		return this.idLink;
	}

	public void setIdLink(int idLink) {
		this.idLink = idLink;
	}

	public Link getLink() {
		return this.link;
	}

	public void setLink(Link link) {
		this.link = link;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPumpCurve() {
		return this.pumpCurve;
	}

	public void setPumpCurve(String pumpCurve) {
		this.pumpCurve = pumpCurve;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public BigDecimal getStartup() {
		return this.startup;
	}

	public void setStartup(BigDecimal startup) {
		this.startup = startup;
	}

	public BigDecimal getShutoff() {
		return this.shutoff;
	}

	public void setShutoff(BigDecimal shutoff) {
		this.shutoff = shutoff;
	}

}
