package centaur.db;
// Generated Mar 16, 2016 11:11:21 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Pump generated by hbm2java
 */
public class Pump implements java.io.Serializable {

	private int idLink;
	private Curve curve;
	private Link link;
	private String status;
	private BigDecimal startup;
	private BigDecimal shutoff;

	public Pump() {
	}

	public Pump(Link link) {
		this.link = link;
	}

	public Pump(Curve curve, Link link, String status, BigDecimal startup, BigDecimal shutoff) {
		this.curve = curve;
		this.link = link;
		this.status = status;
		this.startup = startup;
		this.shutoff = shutoff;
	}

	public int getIdLink() {
		return this.idLink;
	}

	public void setIdLink(int idLink) {
		this.idLink = idLink;
	}

	public Curve getCurve() {
		return this.curve;
	}

	public void setCurve(Curve curve) {
		this.curve = curve;
	}

	public Link getLink() {
		return this.link;
	}

	public void setLink(Link link) {
		this.link = link;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public BigDecimal getStartup() {
		return this.startup;
	}

	public void setStartup(BigDecimal startup) {
		this.startup = startup;
	}

	public BigDecimal getShutoff() {
		return this.shutoff;
	}

	public void setShutoff(BigDecimal shutoff) {
		this.shutoff = shutoff;
	}

}
