package centaur.db;
// Generated 28-Feb-2017 15:38:29 by Hibernate Tools 5.2.0.CR1

/**
 * SimNode generated by hbm2java
 */
public class SimNode implements java.io.Serializable {

	private SimNodeId id;
	private Node node;
	private Simulation simulation;

	public SimNode() {
	}

	public SimNode(SimNodeId id) {
		this.id = id;
	}

	public SimNode(SimNodeId id, Node node, Simulation simulation) {
		this.id = id;
		this.node = node;
		this.simulation = simulation;
	}

	public SimNodeId getId() {
		return this.id;
	}

	public void setId(SimNodeId id) {
		this.id = id;
	}

	public Node getNode() {
		return this.node;
	}

	public void setNode(Node node) {
		this.node = node;
	}

	public Simulation getSimulation() {
		return this.simulation;
	}

	public void setSimulation(Simulation simulation) {
		this.simulation = simulation;
	}

}
