package centaur.db;
// Generated 28-Feb-2017 16:09:34 by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;

/**
 * SimNode generated by hbm2java
 */
public class SimNode implements java.io.Serializable {

	private SimNodeId id;
	private Node node;
	private Simulation simulation;
	private BigDecimal average;
	private BigDecimal stddev;
	private BigDecimal max;
	private BigDecimal min;

	public SimNode() {
	}

	public SimNode(SimNodeId id, Node node, Simulation simulation) {
		this.id = id;
		this.node = node;
		this.simulation = simulation;
	}

	public SimNode(SimNodeId id, Node node, Simulation simulation, BigDecimal average, BigDecimal stddev,
			BigDecimal max, BigDecimal min) {
		this.id = id;
		this.node = node;
		this.simulation = simulation;
		this.average = average;
		this.stddev = stddev;
		this.max = max;
		this.min = min;
	}

	public SimNodeId getId() {
		return this.id;
	}

	public void setId(SimNodeId id) {
		this.id = id;
	}

	public Node getNode() {
		return this.node;
	}

	public void setNode(Node node) {
		this.node = node;
	}

	public Simulation getSimulation() {
		return this.simulation;
	}

	public void setSimulation(Simulation simulation) {
		this.simulation = simulation;
	}

	public BigDecimal getAverage() {
		return this.average;
	}

	public void setAverage(BigDecimal average) {
		this.average = average;
	}

	public BigDecimal getStddev() {
		return this.stddev;
	}

	public void setStddev(BigDecimal stddev) {
		this.stddev = stddev;
	}

	public BigDecimal getMax() {
		return this.max;
	}

	public void setMax(BigDecimal max) {
		this.max = max;
	}

	public BigDecimal getMin() {
		return this.min;
	}

	public void setMin(BigDecimal min) {
		this.min = min;
	}

}
