package centaur.db;
// Generated 28-Feb-2017 16:09:34 by Hibernate Tools 5.2.0.CR1

/**
 * SimNodeId generated by hbm2java
 */
public class SimNodeId implements java.io.Serializable {

	private int idNode;
	private int idSim;

	public SimNodeId() {
	}

	public SimNodeId(int idNode, int idSim) {
		this.idNode = idNode;
		this.idSim = idSim;
	}

	public int getIdNode() {
		return this.idNode;
	}

	public void setIdNode(int idNode) {
		this.idNode = idNode;
	}

	public int getIdSim() {
		return this.idSim;
	}

	public void setIdSim(int idSim) {
		this.idSim = idSim;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SimNodeId))
			return false;
		SimNodeId castOther = (SimNodeId) other;

		return (this.getIdNode() == castOther.getIdNode()) && (this.getIdSim() == castOther.getIdSim());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdNode();
		result = 37 * result + this.getIdSim();
		return result;
	}

}
