package centaur.db;
// Generated 28-Feb-2017 15:38:29 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Simulation generated by hbm2java
 */
public class Simulation implements java.io.Serializable {

	private Integer id;
	private String name;
	private String details;
	private Date date;
	private Set simNodes = new HashSet(0);

	public Simulation() {
	}

	public Simulation(String name) {
		this.name = name;
	}

	public Simulation(String name, String details, Date date, Set simNodes) {
		this.name = name;
		this.details = details;
		this.date = date;
		this.simNodes = simNodes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Set getSimNodes() {
		return this.simNodes;
	}

	public void setSimNodes(Set simNodes) {
		this.simNodes = simNodes;
	}

}
