package centaur.db;
// Generated 25-Jan-2017 14:43:53 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Subcatchment generated by hbm2java
 */
public class Subcatchment implements java.io.Serializable {

	private Integer id;
	private Node node;
	private Raingage raingage;
	private String name;
	private BigDecimal area;
	private BigDecimal imperv;
	private BigDecimal width;
	private BigDecimal slope;
	private BigDecimal curbLen;
	private String snowPack;
	private Serializable geom;
	private Subarea subarea;
	private Set polygons = new HashSet(0);

	public Subcatchment() {
	}

	public Subcatchment(Node node, Raingage raingage, String name, BigDecimal area, BigDecimal imperv, BigDecimal width,
			BigDecimal slope, BigDecimal curbLen, String snowPack, Serializable geom, Subarea subarea, Set polygons) {
		this.node = node;
		this.raingage = raingage;
		this.name = name;
		this.area = area;
		this.imperv = imperv;
		this.width = width;
		this.slope = slope;
		this.curbLen = curbLen;
		this.snowPack = snowPack;
		this.geom = geom;
		this.subarea = subarea;
		this.polygons = polygons;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Node getNode() {
		return this.node;
	}

	public void setNode(Node node) {
		this.node = node;
	}

	public Raingage getRaingage() {
		return this.raingage;
	}

	public void setRaingage(Raingage raingage) {
		this.raingage = raingage;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getArea() {
		return this.area;
	}

	public void setArea(BigDecimal area) {
		this.area = area;
	}

	public BigDecimal getImperv() {
		return this.imperv;
	}

	public void setImperv(BigDecimal imperv) {
		this.imperv = imperv;
	}

	public BigDecimal getWidth() {
		return this.width;
	}

	public void setWidth(BigDecimal width) {
		this.width = width;
	}

	public BigDecimal getSlope() {
		return this.slope;
	}

	public void setSlope(BigDecimal slope) {
		this.slope = slope;
	}

	public BigDecimal getCurbLen() {
		return this.curbLen;
	}

	public void setCurbLen(BigDecimal curbLen) {
		this.curbLen = curbLen;
	}

	public String getSnowPack() {
		return this.snowPack;
	}

	public void setSnowPack(String snowPack) {
		this.snowPack = snowPack;
	}

	public Serializable getGeom() {
		return this.geom;
	}

	public void setGeom(Serializable geom) {
		this.geom = geom;
	}

	public Subarea getSubarea() {
		return this.subarea;
	}

	public void setSubarea(Subarea subarea) {
		this.subarea = subarea;
	}

	public Set getPolygons() {
		return this.polygons;
	}

	public void setPolygons(Set polygons) {
		this.polygons = polygons;
	}

}
