package centaur.db;
// Generated Mar 23, 2016 12:12:19 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * VCandidate generated by hbm2java
 */
public class VCandidate implements java.io.Serializable {

	private Integer id;
	private BigDecimal outflowElevation;
	private String name;
	//private Serializable geom;
	private Double floodedVolume;
	private BigDecimal servedArea;

	public VCandidate() {
	}

	public VCandidate(Integer id) {
		this.id = id;
	}

	public VCandidate(Integer id, BigDecimal outflowElevation, String name, /*Serializable geom,*/ Double floodedVolume,
			BigDecimal servedArea) {
		this.id = id;
		this.outflowElevation = outflowElevation;
		this.name = name;
		//this.geom = geom;
		this.floodedVolume = floodedVolume;
		this.servedArea = servedArea;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BigDecimal getOutflowElevation() {
		return this.outflowElevation;
	}

	public void setOutflowElevation(BigDecimal outflowElevation) {
		this.outflowElevation = outflowElevation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/*public Serializable getGeom() {
		return this.geom;
	}

	public void setGeom(Serializable geom) {
		this.geom = geom;
	}*/

	public Double getFloodedVolume() {
		return this.floodedVolume;
	}

	public void setFloodedVolume(Double floodedVolume) {
		this.floodedVolume = floodedVolume;
	}

	public BigDecimal getServedArea() {
		return this.servedArea;
	}

	public void setServedArea(BigDecimal servedArea) {
		this.servedArea = servedArea;
	}

}
