package centaur.db;
// Generated 01-Feb-2017 16:59:01 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * VCandidate generated by hbm2java
 */
public class VCandidate implements java.io.Serializable {

	private int idNode;
	private BigDecimal outflowElevation;
	private String name;
	//private Serializable geom;
	private Double floodedVolume;
	private BigDecimal servedArea;
	private Long numSubcatchments;
	private Double normFloodedVolume;
	private BigDecimal normServedArea;
	private Double normNumSubcatchments;

	public VCandidate() {
	}

	public VCandidate(int idNode) {
		this.idNode = idNode;
	}

	public VCandidate(int idNode, BigDecimal outflowElevation, String name, /*Serializable geom,*/ Double floodedVolume,
			BigDecimal servedArea, Long numSubcatchments, Double normFloodedVolume, BigDecimal normServedArea,
			Double normNumSubcatchments) {
		this.idNode = idNode;
		this.outflowElevation = outflowElevation;
		this.name = name;
		//this.geom = geom;
		this.floodedVolume = floodedVolume;
		this.servedArea = servedArea;
		this.numSubcatchments = numSubcatchments;
		this.normFloodedVolume = normFloodedVolume;
		this.normServedArea = normServedArea;
		this.normNumSubcatchments = normNumSubcatchments;
	}

	public int getIdNode() {
		return this.idNode;
	}

	public void setIdNode(int idNode) {
		this.idNode = idNode;
	}

	public BigDecimal getOutflowElevation() {
		return this.outflowElevation;
	}

	public void setOutflowElevation(BigDecimal outflowElevation) {
		this.outflowElevation = outflowElevation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/*public Serializable getGeom() {
		return this.geom;
	}

	public void setGeom(Serializable geom) {
		this.geom = geom;
	}*/

	public Double getFloodedVolume() {
		return this.floodedVolume;
	}

	public void setFloodedVolume(Double floodedVolume) {
		this.floodedVolume = floodedVolume;
	}

	public BigDecimal getServedArea() {
		return this.servedArea;
	}

	public void setServedArea(BigDecimal servedArea) {
		this.servedArea = servedArea;
	}

	public Long getNumSubcatchments() {
		return this.numSubcatchments;
	}

	public void setNumSubcatchments(Long numSubcatchments) {
		this.numSubcatchments = numSubcatchments;
	}

	public Double getNormFloodedVolume() {
		return this.normFloodedVolume;
	}

	public void setNormFloodedVolume(Double normFloodedVolume) {
		this.normFloodedVolume = normFloodedVolume;
	}

	public BigDecimal getNormServedArea() {
		return this.normServedArea;
	}

	public void setNormServedArea(BigDecimal normServedArea) {
		this.normServedArea = normServedArea;
	}

	public Double getNormNumSubcatchments() {
		return this.normNumSubcatchments;
	}

	public void setNormNumSubcatchments(Double normNumSubcatchments) {
		this.normNumSubcatchments = normNumSubcatchments;
	}

}
