package centaur.db;
// Generated 19-Jan-2017 14:27:00 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * VJunctionId generated by hbm2java
 */
public class VJunctionId implements java.io.Serializable {

	private Integer id;
	private BigDecimal elevation;
	private String name;
	private Serializable geom;
	private BigDecimal maxDepth;
	private BigDecimal initDepth;
	private BigDecimal surDepth;
	private BigDecimal aponded;
	private Double energySlope;

	public VJunctionId() {
	}

	public VJunctionId(Integer id, BigDecimal elevation, String name, Serializable geom, BigDecimal maxDepth,
			BigDecimal initDepth, BigDecimal surDepth, BigDecimal aponded, Double energySlope) {
		this.id = id;
		this.elevation = elevation;
		this.name = name;
		this.geom = geom;
		this.maxDepth = maxDepth;
		this.initDepth = initDepth;
		this.surDepth = surDepth;
		this.aponded = aponded;
		this.energySlope = energySlope;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BigDecimal getElevation() {
		return this.elevation;
	}

	public void setElevation(BigDecimal elevation) {
		this.elevation = elevation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Serializable getGeom() {
		return this.geom;
	}

	public void setGeom(Serializable geom) {
		this.geom = geom;
	}

	public BigDecimal getMaxDepth() {
		return this.maxDepth;
	}

	public void setMaxDepth(BigDecimal maxDepth) {
		this.maxDepth = maxDepth;
	}

	public BigDecimal getInitDepth() {
		return this.initDepth;
	}

	public void setInitDepth(BigDecimal initDepth) {
		this.initDepth = initDepth;
	}

	public BigDecimal getSurDepth() {
		return this.surDepth;
	}

	public void setSurDepth(BigDecimal surDepth) {
		this.surDepth = surDepth;
	}

	public BigDecimal getAponded() {
		return this.aponded;
	}

	public void setAponded(BigDecimal aponded) {
		this.aponded = aponded;
	}

	public Double getEnergySlope() {
		return this.energySlope;
	}

	public void setEnergySlope(Double energySlope) {
		this.energySlope = energySlope;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VJunctionId))
			return false;
		VJunctionId castOther = (VJunctionId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getElevation() == castOther.getElevation()) || (this.getElevation() != null
						&& castOther.getElevation() != null && this.getElevation().equals(castOther.getElevation())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getGeom() == castOther.getGeom()) || (this.getGeom() != null && castOther.getGeom() != null
						&& this.getGeom().equals(castOther.getGeom())))
				&& ((this.getMaxDepth() == castOther.getMaxDepth()) || (this.getMaxDepth() != null
						&& castOther.getMaxDepth() != null && this.getMaxDepth().equals(castOther.getMaxDepth())))
				&& ((this.getInitDepth() == castOther.getInitDepth()) || (this.getInitDepth() != null
						&& castOther.getInitDepth() != null && this.getInitDepth().equals(castOther.getInitDepth())))
				&& ((this.getSurDepth() == castOther.getSurDepth()) || (this.getSurDepth() != null
						&& castOther.getSurDepth() != null && this.getSurDepth().equals(castOther.getSurDepth())))
				&& ((this.getAponded() == castOther.getAponded()) || (this.getAponded() != null
						&& castOther.getAponded() != null && this.getAponded().equals(castOther.getAponded())))
				&& ((this.getEnergySlope() == castOther.getEnergySlope())
						|| (this.getEnergySlope() != null && castOther.getEnergySlope() != null
								&& this.getEnergySlope().equals(castOther.getEnergySlope())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getElevation() == null ? 0 : this.getElevation().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getGeom() == null ? 0 : this.getGeom().hashCode());
		result = 37 * result + (getMaxDepth() == null ? 0 : this.getMaxDepth().hashCode());
		result = 37 * result + (getInitDepth() == null ? 0 : this.getInitDepth().hashCode());
		result = 37 * result + (getSurDepth() == null ? 0 : this.getSurDepth().hashCode());
		result = 37 * result + (getAponded() == null ? 0 : this.getAponded().hashCode());
		result = 37 * result + (getEnergySlope() == null ? 0 : this.getEnergySlope().hashCode());
		return result;
	}

}
