package centaur.db;
// Generated 19-Jan-2017 14:29:58 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * VJunction generated by hbm2java
 */
public class VJunction implements java.io.Serializable {

	private Integer id;
	private BigDecimal elevation;
	private String name;
	//private Serializable geom;
	private BigDecimal maxDepth;
	private BigDecimal initDepth;
	private BigDecimal surDepth;
	private BigDecimal aponded;
	private Double energySlope;

	public VJunction() {
	}

	public VJunction(Integer id) {
		this.id = id;
	}

	public VJunction(Integer id, BigDecimal elevation, String name, /*Serializable geom,*/ BigDecimal maxDepth,
			BigDecimal initDepth, BigDecimal surDepth, BigDecimal aponded, Double energySlope) {
		this.id = id;
		this.elevation = elevation;
		this.name = name;
		//this.geom = geom;
		this.maxDepth = maxDepth;
		this.initDepth = initDepth;
		this.surDepth = surDepth;
		this.aponded = aponded;
		this.energySlope = energySlope;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BigDecimal getElevation() {
		return this.elevation;
	}

	public void setElevation(BigDecimal elevation) {
		this.elevation = elevation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/*public Serializable getGeom() {
		return this.geom;
	}

	public void setGeom(Serializable geom) {
		this.geom = geom;
	}*/

	public BigDecimal getMaxDepth() {
		return this.maxDepth;
	}

	public void setMaxDepth(BigDecimal maxDepth) {
		this.maxDepth = maxDepth;
	}

	public BigDecimal getInitDepth() {
		return this.initDepth;
	}

	public void setInitDepth(BigDecimal initDepth) {
		this.initDepth = initDepth;
	}

	public BigDecimal getSurDepth() {
		return this.surDepth;
	}

	public void setSurDepth(BigDecimal surDepth) {
		this.surDepth = surDepth;
	}

	public BigDecimal getAponded() {
		return this.aponded;
	}

	public void setAponded(BigDecimal aponded) {
		this.aponded = aponded;
	}

	public Double getEnergySlope() {
		return this.energySlope;
	}

	public void setEnergySlope(Double energySlope) {
		this.energySlope = energySlope;
	}

}
