DELETE FROM centaur.coordinates;
DELETE FROM centaur.polygon;
DELETE FROM centaur.outfall;
DELETE FROM centaur.junction;
DELETE FROM centaur.storage;
DELETE FROM centaur.subarea;
DELETE FROM centaur.subcatchment;
DELETE FROM centaur.raingage;
DELETE FROM centaur.pump;
DELETE FROM centaur.weir;
DELETE FROM centaur.conduit;
DELETE FROM centaur.xsection;
DELETE FROM centaur.link;
DELETE FROM centaur.node;
DELETE FROM centaur.curve_parameter;
DELETE FROM centaur.curve;
DELETE FROM centaur.flooded;
DELETE FROM centaur.candidate;

