CREATE GROUP CENTAUR;

CREATE USER jpcarbajal PASSWORD '1234' LOGIN IN GROUP CENTAUR;

CREATE USER jrieckermann PASSWORD '1234' LOGIN IN GROUP CENTAUR; 

CREATE USER jpleitao PASSWORD '1234' LOGIN IN GROUP CENTAUR; 

CREATE USER test PASSWORD '1234' LOGIN IN GROUP CENTAUR; 

 



